### ISSUE TITLE
Multiple threads failed

### ISSUE THREAD

**Issue by JinyuanSun** [Gangl2016/Optimal-growth-temperture-predictor#3]
Command: tome predOGT --fasta BacDive_Tome_Thermo.fasta --threads 0

/home/jsun/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
FileName	predOGT (C)
Traceback (most recent call last):
  File "/home/jsun/anaconda3/bin/tome", line 11, in <module>
    load_entry_point('tome', 'console_scripts', 'tome')()
  File "/home/jsun/depect/thermoprotein/Tome/tome/tome.py", line 106, in main
    else: predOGT.main(args)
  File "/home/jsun/depect/thermoprotein/Tome/tome/core/predOGT.py", line 192, in main
    pred_ogt = predict(infile,model,means,stds,features,args.threads)
  File "/home/jsun/depect/thermoprotein/Tome/tome/core/predOGT.py", line 170, in predict
    dimers_fq = get_dimer_frequency(fasta_file,p)
  File "/home/jsun/depect/thermoprotein/Tome/tome/core/predOGT.py", line 156, in get_dimer_frequency
    dimers = count_dimer(fasta_file,p)
  File "/home/jsun/depect/thermoprotein/Tome/tome/core/predOGT.py", line 151, in count_dimer
    results = Pool(num_cpus).map(do_count, seqs)
  File "/home/jsun/anaconda3/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/jsun/anaconda3/lib/python3.7/multiprocessing/pool.py", line 168, in __init__
    if processes < 1:
TypeError: '<' not supported between instances of 'str' and 'int'

Is that a type error because the code did not convert processes to int or I used it in a wrong way?

**Comment by mengqvist** [comment]
Ah yes, it indeed seems that the string was never converted to int. I have fixed this now and the code runs correctly on my test file. #

**Comment by mengqvist** [comment]
I will mark this as closed. If you continue having issues with the modified code I can re-open again.
