### ISSUE TITLE
Use scikit-learn instead sklearn

### ISSUE THREAD

**Issue by bj600800** [Gangl2016/Optimal-growth-temperture-predictor#5]
Modify setup.py from sklearn to scikit-learn

**Comment by Valentin-Bio** [comment]
Still modifying that in the setup.py file makes the program to fail for me when I run tome program:

> Traceback (most recent call last):
  File "/opt/Tome_venv/bin/tome", line 33, in <module>
    sys.exit(load_entry_point('tome==2.0.0', 'console_scripts', 'tome')())
  File "/opt/Tome_venv/lib64/python3.9/site-packages/tome/tome.py", line 104, in main
    from tome.core import predOGT
  File "/opt/Tome_venv/lib64/python3.9/site-packages/tome/core/predOGT.py", line 23, in <module>
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (/opt/Tome_venv/lib64/python3.9/site-packages/sklearn/externals/__init__.py)
Traceback (most recent call last):
  File "/opt/Tome_venv/bin/tome", line 33, in <module>
    sys.exit(load_entry_point('tome==2.0.0', 'console_scripts', 'tome')())
  File "/opt/Tome_venv/lib64/python3.9/site-packages/tome/tome.py", line 104, in main
    from tome.core import predOGT
  File "/opt/Tome_venv/lib64/python3.9/site-packages/tome/core/predOGT.py", line 23, in <module>
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (/opt/Tome_venv/lib64/python3.9/site-packages/sklearn/externals/__init__.py)
Traceback (most recent call last):
  File "/opt/Tome_venv/bin/tome", line 33, in <module>
    sys.exit(load_entry_point('tome==2.0.0', 'console_scripts', 'tome')())
  File "/opt/Tome_venv/lib64/python3.9/site-packages/tome/tome.py", line 104, in main
    from tome.core import predOGT
  File "/opt/Tome_venv/lib64/python3.9/site-packages/tome/core/predOGT.py", line 23, in <module>
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (/opt/Tome_venv/lib64/python3.9/site-packages/sklearn/externals/__init__.py)

**Comment by Valentin-Bio** [comment]
corrected by doing #6
